### ISSUE TITLE
_pickle.UnpicklingError: the STRING opcode argument must be quoted

### ISSUE THREAD

**Issue by tjb-tech** [tsinghua-fib-lab/Traffic-Benchmark#5]
你好，在运行这个项目时为什么会有这个报错，求大佬解答！

完整报错如下：
/content/drive/MyDrive/Traffic-Benchmark
Traceback (most recent call last):
  File "./methods/DCRNN/dcrnn_train_pytorch.py", line 35, in <module>
    main(args)
  File "./methods/DCRNN/dcrnn_train_pytorch.py", line 18, in main
    sensor_ids, sensor_id_to_ind, adj_mx = load_graph_data(graph_pkl_filename)
  File "/content/drive/MyDrive/Traffic-Benchmark/methods/DCRNN/lib/utils.py", line 198, in load_graph_data
    sensor_ids, sensor_id_to_ind, adj_mx = load_pickle(pkl_filename)
  File "/content/drive/MyDrive/Traffic-Benchmark/methods/DCRNN/lib/utils.py", line 205, in load_pickle
    pickle_data = pickle.load(f)
_pickle.UnpicklingError: the STRING opcode argument must be quoted

**Comment by zbq-01s** [comment]
因为你的Python版本和作者的代码使用的版本不一致，因此生成的文件adj_mx.pkl也会出现读取错误

**Comment by zhiqianguan** [comment]
![image](https://user-images.githubusercontent.com/37625373/197335921-67549f81-2c86-4ffd-8a6f-aa8aec7ff8b6.png)
![image](https://user-images.githubusercontent.com/37625373/197335935-19dd8bdb-aa22-4a84-8045-aa530033e4c7.png)
